<?php

namespace Owl\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    public function getServices($limit = 4)
    {
        $service = $this->createQueryBuilder('b')
                        ->select('b')
                        ->addOrderBy('b.sort', 'ASC');

        if(false === is_null($limit)) {
            $service->setMaxResults($limit);
        }

        return $service->getQuery()->getResult();
    }
}
